config/routes.rb
Rails.application.routes.draw do
  resources :heros
  resources :cars
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/car.rb
class Car < ApplicationRecord
  has_many :hero
end

app/models/hero.rb
class Hero < ApplicationRecord
  belongs_to :car
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :set_car, only: [:show, :edit, :update, :destroy]

  # GET /cars
  # GET /cars.json
  def index
    @cars = Car.all
  end

  # GET /cars/1
  # GET /cars/1.json
  def show
  end

  # GET /cars/new
  def new
    @car = Car.new
  end

  # GET /cars/1/edit
  def edit
  end

  # POST /cars
  # POST /cars.json
  def create
    @car = Car.new(car_params)

    respond_to do |format|
      if @car.save
        format.html { redirect_to @car, notice: 'Car was successfully created.' }
        format.json { render :show, status: :created, location: @car }
      else
        format.html { render :new }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cars/1
  # PATCH/PUT /cars/1.json
  def update
    respond_to do |format|
      if @car.update(car_params)
        format.html { redirect_to @car, notice: 'Car was successfully updated.' }
        format.json { render :show, status: :ok, location: @car }
      else
        format.html { render :edit }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cars/1
  # DELETE /cars/1.json
  def destroy
    @car.destroy
    respond_to do |format|
      format.html { redirect_to cars_url, notice: 'Car was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_car
      @car = Car.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def car_params
      params.require(:car).permit(:name, :make, :model, :year, :color)
    end
end

app/controllers/heros_controller.rb
class HerosController < ApplicationController
  before_action :set_hero, only: [:show, :edit, :update, :destroy]

  # GET /heros
  # GET /heros.json
  def index
    @heros = Hero.all
  end

  # GET /heros/1
  # GET /heros/1.json
  def show
  end

  # GET /heros/new
  def new
    @hero = Hero.new
  end

  # GET /heros/1/edit
  def edit
  end

  # POST /heros
  # POST /heros.json
  def create
    @hero = Hero.new(hero_params)

    respond_to do |format|
      if @hero.save
        format.html { redirect_to @hero, notice: 'Hero was successfully created.' }
        format.json { render :show, status: :created, location: @hero }
      else
        format.html { render :new }
        format.json { render json: @hero.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /heros/1
  # PATCH/PUT /heros/1.json
  def update
    respond_to do |format|
      if @hero.update(hero_params)
        format.html { redirect_to @hero, notice: 'Hero was successfully updated.' }
        format.json { render :show, status: :ok, location: @hero }
      else
        format.html { render :edit }
        format.json { render json: @hero.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /heros/1
  # DELETE /heros/1.json
  def destroy
    @hero.destroy
    respond_to do |format|
      format.html { redirect_to heros_url, notice: 'Hero was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hero
      @hero = Hero.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hero_params
      params.require(:hero).permit(:first_name, :last_name, :alias, :address, :city, :state, :car_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/heros_helper.rb
module HerosHelper
end

app/views/cars/_form.html.erb
<%= form_with(model: car, local: true) do |form| %>
  <% if car.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(car.errors.count, "error") %> prohibited this car from being saved:</h2>

      <ul>
      <% car.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :make %>
    <%= form.text_field :make %>
  </div>

  <div class="field">
    <%= form.label :model %>
    <%= form.text_field :model %>
  </div>

  <div class="field">
    <%= form.label :year %>
    <%= form.text_field :year %>
  </div>

  <div class="field">
    <%= form.label :color %>
    <%= form.text_field :color %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/cars/edit.html.erb
<h1>Editing Car</h1>
<p class="navbar">
</p>

<%= render 'form', car: @car %>

<%= link_to 'Show', @car %> |
<%= link_to 'Back', cars_path %>

app/views/cars/index.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'HEROES', heros_path %></h1>
 <h1>CARS</h1>
<p class=navbar>

<p/>



<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Make</th>
      <th>Model</th>
      <th>Year</th>
      <th>Color</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cars.each do |car| %>
      <tr>
        <td><%= car.name %></td>
        <td><%= car.make %></td>
        <td><%= car.model %></td>
        <td><%= car.year %></td>
        <td><%= car.color %></td>
        <td><%= link_to 'Show', car %></td>
        <td><%= link_to 'Edit', edit_car_path(car) %></td>
        <td><%= link_to 'Remove', car, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Car', new_car_path %>

app/views/cars/new.html.erb
<h1>New Car</h1>
<p class="navbar">
</p>

<h3>NOTE: Please Create CAR BEFORE creating a HERO [!We are under construction!]</h3>

<%= render 'form', car: @car %>

<%= link_to 'Back', cars_path %>

app/views/cars/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @car.name %>
</p>

<p>
  <strong>Make:</strong>
  <%= @car.make %>
</p>

<p>
  <strong>Model:</strong>
  <%= @car.model %>
</p>

<p>
  <strong>Year:</strong>
  <%= @car.year %>
</p>

<p>
  <strong>Color:</strong>
  <%= @car.color %>
</p>

<%= link_to 'Edit', edit_car_path(@car) %> |
<%= link_to 'Back', cars_path %>

app/views/heros/_form.html.erb
<%= form_with(model: hero, local: true) do |form| %>
  <% if hero.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(hero.errors.count, "error") %> prohibited this hero from being saved:</h2>

      <ul>
      <% hero.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>

  <div class="field">
    <%= form.label :alias %>
    <%= form.text_field :alias %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

  <div class="field">
    <%= form.label :city %>
    <%= form.text_field :city %>
  </div>

  <div class="field">
    <%= form.label :state %>
    <%= form.text_field :state %>
  </div>

  <div class="field">
    <%= form.label :car_id %>
    <%= form.collection_select :car_id, Car.all, :id, :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/heros/edit.html.erb
<h1>Editing Hero</h1>

<%= render 'form', hero: @hero %>

<%= link_to 'Show', @hero %> |
<%= link_to 'Back', heros_path %>

app/views/heros/index.html.erb
<p id="notice"><%= notice %></p>
<%= link_to 'CARS', cars_path %>

<h1>Heroes</h1>
<p class=navbar>


<p/>


<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Alias</th>
      <th>Address</th>
      <th>City</th>
      <th>State</th>
      <th>Car</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @heros.each do |hero| %>
      <tr>
        <td><%= hero.first_name %></td>
        <td><%= hero.last_name %></td>
        <td><%= hero.alias %></td>
        <td><%= hero.address %></td>
        <td><%= hero.city %></td>
        <td><%= hero.state %></td>
        <td><%= hero.car.name %></td>
        <td><%= link_to 'Show', hero %></td>
        <td><%= link_to 'Edit', edit_hero_path(hero) %></td>
        <td><%= link_to 'Remove', hero, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Hero', new_hero_path %>

app/views/heros/new.html.erb
<h1>New Hero</h1>
<p class="navbar">
 </p>

<h3>NOTE: Please Create CAR BEFORE creating a HERO [!We are under construction!]</h3>
<%= render 'form', hero: @hero %>

<%= link_to 'Back', heros_path %>

app/views/heros/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @hero.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @hero.last_name %>
</p>

<p>
  <strong>Alias:</strong>
  <%= @hero.alias %>
</p>

<p>
  <strong>Address:</strong>
  <%= @hero.address %>
</p>

<p>
  <strong>City:</strong>
  <%= @hero.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @hero.state %>
</p>

<p>
  <strong>Car:</strong>
  <%= @hero.car.name %>
</p>

<%= link_to 'Edit', edit_hero_path(@hero) %> |
<%= link_to 'Back', heros_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RubyCalculatorGitActivity</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>